version: '3.8'

services:
  typograph_back:
    container_name: typograph_back
    build: ./
    ports:
      - "${TYPOGRAPH_SERVICE_PORT}:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - typograph-db
    env_file:
      - .env

  typograph-db:
    container_name: typograph-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${TYPOGRAPH_SERVICE_DB_PORT}:5432"
    volumes:
      - typograph-db:/var/lib/postgresql/data

volumes:
  typograph-db:
