version: '3.8'
name: tp_prod

services:
  nginx:
    container_name: tp_nginx
    build: 
      context: .
      dockerfile: ./docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - typograph_back
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  typograph_back:
    container_name: typograph_back
    build: 
      context: .
      dockerfile: ./docker/prod.dockerfile
    ports:
      - "${TYPOGRAPH_SERVICE_PORT}:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - typograph-db
    env_file:
      - .env

  typograph-db:
    container_name: typograph-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${TYPOGRAPH_SERVICE_DB_PORT}:5432"
    volumes:
      - typograph-db:/var/lib/postgresql/data

volumes:
  typograph-db:
